### ISSUE TITLE
Massive data by suing mget

### ISSUE THREAD

**Issue by gblue1223** [falsecz/node-hbase#2]
Hello, 

I've tried to get more than 200,000 rows from hbase  at once by mget of node-hbase.
But when I tried to get data, timeout event occurred.

Should I slice the data? or which code should I look at to modify?

**Comment by wision** [comment]
Hello,

if scan is viable option for you, I'd suggest to use that, since it's not trying to get all the results at once. Otherwise yes, you should change the size of the batch and try to get smaller number of rows per mget, or you can increase call timeout, which I don't think it's good idea.

**Comment by gblue1223** [comment]
Thank you for fast reply.
How about mput? Is there another option like scan?

**Comment by wision** [comment]
Nope.. you have to split your request into smaller batches (or increase call timeout).
Protobufs do support batch requests.
As I don't have any benchmark data, I cannot tell you if thrift will perform any better.
