### ISSUE TITLE
Regions not being updated

### ISSUE THREAD

**Issue by Pampattitude** [falsecz/node-hbase#5]
Hi again!

I'm having another issue with your [awesome!] module. HBase sometimes updates regions, but the changes don't seem to be propagated to the module.

After a while (usually close to every day), specific HBase regions get all the requests. Restarting the client (so restarting the Node.js application) fixes the problem.
Is there a way to update the regions?

You can test it out by doing the HBase split manually.

Thanks a bunch for your help!
Regards,

**Comment by wision** [comment]
Hello,
thank you for reporting. Issue was fixed: https://github.com/falsecz/node-hbase/pull/6
